timm             make dist/build/all.valid.xml.bin/all.valid.xml                       RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Unit tests/**'"
timm timeout 3h  make dist/build/delay.valid.xml.bin/delay.valid.xml                   RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm timeout 2h  make dist/build/soundness.valid.xml.bin/soundness.valid.xml           RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/wod.valid.xml.bin/wod.valid.xml                       RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/indeps.valid.xml.bin/indeps.valid.xml                 RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/cdom.valid.xml.bin/cdom.valid.xml                     RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/nticd.valid.xml.bin/nticd.valid.xml                   RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/ntscd.valid.xml.bin/ntscd.valid.xml                   RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/balanced.valid.xml.bin/balanced.valid.xml             RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/timing.valid.xml.bin/timing.valid.xml                 RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/timingDep.valid.xml.bin/timingDep.valid.xml           RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/simon.valid.xml.bin/simon.valid.xml                   RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/giffhorn.valid.xml.bin/giffhorn.valid.xml             RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/preccex.valid.xml.bin/preccex.valid.xml               RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/newcd.valid.xml.bin/newcd.valid.xml                   RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/dod.valid.xml.bin/dod.valid.xml                       RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/color.valid.xml.bin/color.valid.xml                   RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/reducible.valid.xml.bin/reducible.valid.xml           RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/insensitiveDom.valid.xml.bin/insensitiveDom.valid.xml RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/cache.valid.xml.bin/cache.valid.xml                   RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/crypto.valid.xml.bin/crypto.valid.xml                 RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
timm             make dist/build/misc.valid.xml.bin/misc.valid.xml                     RTS="+RTS -M22288m  -RTS" PATTERN="-p '**/Properties/**'"
